
spring:
#  config:
#    import: "optional:nacos:config-server.yml"
  cloud:
    consul:
      port: 8500
      host: localhost
    nacos:
      config:
        import-check:
          enabled: false
server:
  port: 8000
