
spring:
  config:
    import: "optional:nacos:"
  cloud:
    consul:
      port: 8500
      host: localhost
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
  application:
    name: config-server
  profiles:
    active: dev
server:
  port: 8000
