
spring:
  config:
    import: optional:nacos:config-server-dev.yml
  cloud:
    consul:
      port: 8500
      host: localhost
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yml
        group: DEFAULT_GROUP
        refresh-enabled: true
        namespace: example-data
        name: config-server
        enable-remote-sync-config: true
        extension-configs:
          - data-id: config-server-dev.yml
            refresh: true
  application:
    name: config-server
  profiles:
    active: dev
server:
  port: 8000