
spring:
  profiles:
    active: home
  application:
    name: api-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.65.116:3306/auth-admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: admin
    password: authadmin
  data:
    redis:
      host: 192.168.160.137
      port: 6379
      client-type: lettuce
      connect-timeout: 30
      timeout: 100
      password: 123456
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
    consul:
      port: 8500
      host: 192.168.160.137
      discovery:
        service-name: ${spring.application.name}
logging:
  level:
    org.springframework.security: trace
    org.springframework.jdbc: debug
server:
  port: 3000