
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.65.116:3306/auth-admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: admin
    password: authadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  application:
    name: api-upms
  profiles:
    active: home
server:
  port: 8002
security:
  oauth2:
    resource:
      ignores:
        urls: 12,123,1241,12515