spring:
  cloud:
    consul:
      host: 192.168.36.129
    nacos:
      config:
        server-addr: 192.168.36.129:8848
  data:
    redis:
      port: 6379
      host: 192.168.36.129
      connect-timeout: 10s
      timeout: 10s
      client-type: lettuce
      password: 123456