spring:
  cloud:
    consul:
      port: 8500
      host: 192.168.160.137
      discovery:
        service-name: ${spring.application.name}
  data:
    redis:
      port: 6379
      host: 192.168.160.137
      connect-timeout: 10s
      timeout: 10s
      client-type: lettuce
      password: 123456