
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
    consul:
      port: 8500
      host: 192.168.160.137
      discovery:
        service-name: ${spring.application.name}
  data:
    redis:
      port: 6379
      host: 192.168.160.137
      connect-timeout: 10s
      timeout: 10s
      client-type: lettuce
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth-admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  application:
    name: api-upms
server:
  port: 8002
security:
  oauth2:
    resource:
      ignores:
        urls: 12,123,1241,12515