version: "3"
services:
  consul:
    container_name: consul
    image: hashicorp/consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
  redis:
    restart: always
    logging:
      options:
        max-size: 100m
        max-file: 2
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - /home/linux/Documents/redis/redis.conf:/etc/redis/redis.conf
      - /home/linux/Documents/redis/data:/data
    image: redis
    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass
      123456