
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
    consul:
      port: 8500
      host: 192.168.36.129
      discovery:
        service-name: ${spring.application.name}
  data:
    redis:
      port: 6379
      host: 192.168.36.129
      connect-timeout: 10s
      timeout: 10s
      client-type: lettuce
      password: 123456
  application:
    name: system
server:
  port: 8002