

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
  application:
    name: system
server:
  port: 8002